package visitor;

import AST.ArrayLength;
import AST.Times;
import AST.Declaraciones2;
import AST.MoreThan;
import AST.IdentifierExp;
import AST.LessThan;
import AST.MoreThanEqual;
import AST.CharArrayType;
import AST.Asignar;
import AST.FloatArrayType;
import AST.Modules;
import AST.If;
import AST.Equal;
import AST.False;
import AST.CharType;
import AST.IdentifierType;
import AST.And;
import AST.IntegerType;
import AST.Formal;
import AST.ArrayLookup;
import AST.Program;
import AST.Identificadores;
import AST.While;
import AST.Not;
import AST.NewArray;
import AST.LessThanEqual;
import AST.Declaraciones;
import AST.NotEqual;
import AST.Plus;
import AST.Declaraciones3;
import AST.Bloque;
import AST.BooleanArrayType;
import AST.ArrayAssign;
import AST.BooleanType;
import AST.IntegerLiteral;
import AST.Or;
import AST.CharLiteral;
import AST.Divide;
import AST.BooleanLiteral;
import AST.FloatType;
import AST.Negative;
import AST.FloatLiteral;
import AST.True;
import AST.Minus;
import AST.IntegerArrayType;
import javax.swing.JTextArea;

public interface Visitor {
	public void visit(Program prog, JTextArea console);
	public void visit(Declaraciones3 var);
	public void visit(Declaraciones2 varList);
	public void visit(Declaraciones dec, JTextArea console);
	public void visit(Formal param);
	public void visit(IntegerArrayType intArrayT);
	public void visit(FloatArrayType floatArrayT);
	public void visit(BooleanArrayType booleanArrayT);
	public void visit(CharArrayType charArrayT);
	public void visit(BooleanType boolT);
	public void visit(IntegerType intT);
	public void visit(FloatType floatT);
	public void visit(CharType charT);
	public void visit(IdentifierType idT);
	public void visit(Bloque blockStm);
	public void visit(If ifStm);
	public void visit(While whileStm);
	public void visit(Asignar assignStm);
	public void visit(ArrayAssign arrayAssignStm);
	public void visit(And andExp);
	public void visit(Or orExp);
	public void visit(MoreThan moreExp);
	public void visit(LessThan lessThanExp);
	public void visit(Equal equalExp);
	public void visit(NotEqual notEqualExp);
	public void visit(MoreThanEqual moreEqualExp);
	public void visit(LessThanEqual lessEqualExp);
	public void visit(Plus plusExp);
	public void visit(Minus minusExp);
	public void visit(Times timesExp);
	public void visit(Divide divExp);
	public void visit(Modules modExp);
	public void visit(ArrayLookup arrayLookup);
	public void visit(ArrayLength length);
	public void visit(IntegerLiteral intLiteral);
	public void visit(FloatLiteral floatLiteral);
	public void visit(BooleanLiteral booleanLiteral);
	public void visit(CharLiteral charLiteral);
	public void visit(True trueLiteral);
	public void visit(False falseLiteral);
	public void visit(IdentifierExp identExp);
	public void visit(NewArray array);
	public void visit(Not notExp);
	public void visit(Negative negExp);
	public void visit(Identificadores id);
}